language: python

python: 3.5
env:
    - TOXENV=py27
    - TOXENV=py33
    - TOXENV=py34
    - TOXENV=py35
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=coverage
    - TOXENV=pep8
    - TOXENV=docs
install:
    - pip install tox
    - if [ "$TOXENV" = 'coverage' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'coverage' ]; then coveralls; fi
