language: python

env:
    - TOXENV=py27
    - TOXENV=py34
    - TOXENV=pypy
    - TOXENV=pypy3
    - TOXENV=coverage
install:
    - pip install tox
    - if [ "$TOXENV" = 'coverage' ]; then pip install coveralls; fi
script:
    - tox -e $TOXENV
after_success:
    - if [ "$TOXENV" = 'coverage' ]; then coveralls; fi
